name: microbench

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  microbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"

      - name: Microbench (smoke)
        run: |
          python - <<'PY'
          import time
          import numpy as np
          from ssp.p1_detect.score_nonml import score_nonml_windows

          n, t, d = 2048, 64, 16
          x = np.random.default_rng(0).normal(size=(n, t, d)).astype(np.float64)
          t0 = time.perf_counter()
          s = score_nonml_windows(x)
          dt = time.perf_counter() - t0
          print("score_nonml_windows:", s.shape, "seconds:", dt)
          PY
